### PR TITLE
WIP disable commit-message-incrementing

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by SimonCropp** [comment]
so the versioning is broken due to this commit https://github.com/Particular/NServiceBus.AzureBlobStorageDataBus/commit/b62196a9894997d1647d9c35046f6c6230e1c964 

@danielmarbach @andreasohlund re-write history?

**Comment by andreasohlund** [comment]
Is there no way to force it with a temp TAG or something for now? (Not against a force push if needed though)

**Comment by danielmarbach** [comment]
So this PR doesn't address it?

**Comment by andreasohlund** [comment]
No since in this case the release branch was merged into develop
prematurely (ie no bump in commit message)

**Comment by danielmarbach** [comment]
Then let's add a tag.

**Pull request merged**
